root:
  resource: AccountingApiBundle\Controller\DefaultController
  prefix: /
  type: rest

auth:
  resource: AccountingApiBundle\Controller\AuthController
  prefix: /auth
  type: rest

users:
  resource: AccountingApiBundle\Controller\UsersController
  type: rest

my_purses:
  type: rest
  prefix: /users/me
  resource: AccountingApiBundle\Controller\MyPursesController

my_purse_operations:
  type: rest
  parent: my_purses
  resource: AccountingApiBundle\Controller\MyPurseOperationsController

my_categories:
  type: rest
  prefix: /users/me
  resource: AccountingApiBundle\Controller\MyCategoriesController