services:
  forms.entity_form_factory:
      class: AccountingApiBundle\Services\EntityFormFactory

  forms.entity_form:
      class: AccountingApiBundle\Services\EntityForm
      factory: ['@forms.entity_form_factory', createEntityForm]
      arguments: [ "@service_container" ]

  security.jwt:
      class: AccountingApiBundle\Services\JWT
      arguments: [ "%secret%" ]

  access_token_user_provider:
      class: AccountingApiBundle\Security\AccessTokenUserProvider
      arguments: [ "@service_container" ]

  apikey_authenticator:
      class:  AccountingApiBundle\Security\JWTAuthenticator
      arguments: [ "@security.jwt", "@security.http_utils" ]
      public: false

  request_filtering:
      class:  AccountingApiBundle\Services\RequestFiltering