language: php

php:
    - 5.5
    - 5.6
    - 7.0

env:
  - DB=mysql

before_script:
  - mysql -e 'create database IF NOT EXISTS accounting'
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install --dev
  - php app/console doctrine:schema:create --env=test

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v