language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - npm install -g bower
  - npm install
  - bower install
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install --dev
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
  - php app/console assetic:dump

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email:
    on_failure: always

cache:
  directories:
    - vendor
    - $HOME/.composer/cache