NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

app_back_end:
    resource: "@AccountingApiBundle/Resources/config/routing.yml"
    type: rest
    prefix:   /api