NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

app_back_end:
    resource: "@AppBackEndBundle/Resources/config/routing.yml"
    type: rest
    prefix:   /api

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /