# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    encoders:
        AccountingApiBundle\Entity\User:
            algorithm: bcrypt

    providers:
        access_token_user_provider:
            id: access_token_user_provider
        db_provider:
            entity:
                class: AccountingApiBundle:User
                property: name

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_info:
            pattern: ^/api/$
            anonymous: ~

        api_login:
            pattern: ^/api/auth/login
            anonymous: ~

        api_doc:
            pattern: ^/api/doc
            anonymous: ~

        secured_area:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
            provider: access_token_user_provider
