# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    encoders:
        AppBackEndBundle\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: AppBackEndBundle:User
                property: name

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern:    ^/api23
            http_basic: ~
            provider: db_provider