<?php

namespace AppBackEndBundle\Repository;

/**
 * OperationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationsRepository extends \Doctrine\ORM\EntityRepository
{
}
