<?php

namespace AppBackEndBundle\Repository;

/**
 * PursesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PursesRepository extends \Doctrine\ORM\EntityRepository
{
}
