auth:
  resource: AppBackEndBundle\Controller\AuthController
  prefix: /auth
  type: rest

users:
  resource: AppBackEndBundle\Controller\UsersController
  type: rest

my_purses:
  type: rest
  prefix: /users/me
  resource: AppBackEndBundle\Controller\MyPursesController

my_purse_operations:
  type: rest
  parent: my_purses
  resource: AppBackEndBundle\Controller\MyPurseOperationsController

my_categories:
  type: rest
  prefix: /users/me
  resource: AppBackEndBundle\Controller\MyCategoriesController