services:
  forms.entity_form_factory:
      class: AppBackEndBundle\Services\EntityFormFactory

  forms.entity_form:
      class: AppBackEndBundle\Services\EntityForm
      factory: ['@forms.entity_form_factory', createEntityForm]
      arguments: [ "@service_container" ]

  security.jwt:
      class: AppBackEndBundle\Services\JWT
      arguments: [ "%secret%" ]

  access_token_user_provider:
      class: AppBackEndBundle\Security\AccessTokenUserProvider
      arguments: [ "@service_container" ]

  apikey_authenticator:
      class:  AppBackEndBundle\Security\JWTAuthenticator
      arguments: [ "@security.jwt", "@security.http_utils" ]
      public: false