services:
  form.errors_formatter:
      class: AppBackEndBundle\Services\FormErrorsFormatter
      arguments: [ '@service_container' ]

  security.user_jwt:
      class: AppBackEndBundle\Services\JWTUserAuth
      arguments: [ "%secret%", "%jwt_expiration_time%" ]

  access_token_user_provider:
      class: AppBackEndBundle\Security\AccessTokenUserProvider
      arguments: [ "@service_container" ]

  apikey_authenticator:
      class:  AppBackEndBundle\Security\JWTAuthenticator
      arguments: [ "@security.user_jwt", "@security.http_utils" ]
      public: false