<?php

namespace AccountingApiBundle\Repository;

/**
 * CategoriesRepository
 *
 * @codeCoverageIgnore
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUserId($userId, $returnQuery = false)
    {
        $qb = $this
            ->createQueryBuilder('cat');

        $query = $qb
            ->leftJoin('cat.user', 'cat_user')
            ->where('cat_user.id=:user_id')
            ->orWhere($qb->expr()->eq('cat.global', $qb->expr()->literal(true)))
            ->setParameter('user_id', $userId);

        if ($returnQuery) {
            return $query;
        }

        return $query
            ->qetQuery()
            ->getResult();
    }

    public function findByIdAndUserId($categoryId, $userId)
    {
        $qb = $this
            ->createQueryBuilder('cat');

        $category = $qb
            ->leftJoin('cat.user', 'cat_user')
            ->where('cat.id=:category_id')
            ->andWhere(
                $qb
                    ->expr()
                    ->orX()
                    ->add(
                        $qb->expr()->eq('cat.global', $qb->expr()->literal(true))
                    )
                    ->add(
                        $qb->expr()->eq('cat_user.id', ':user_id')
                    )
            )
            ->setParameter('user_id', $userId)
            ->setParameter('category_id', $categoryId)
            ->getQuery()
            ->getOneOrNullResult();

        return $category;
    }
}
